version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/SiemensApp"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: "nuget"
    directory: "/SiemensApp.Tests"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "nuget"
      - "tests"
    commit-message:
      prefix: "chore(deps-tests)"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(actions)"
